repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
-   repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
    -   id: black
-   repo: https://github.com/pycqa/pylint
    rev: v3.0.1
    hooks:
    -   id: pylint
        additional_dependencies:
        - dune-client==1.7.3
        args:
        - --disable=all
        - --enable=E0401
        - --errors-only
        - src/fetch/dune.py:10:0,E0401
        - src/fetch/dune.py:11:0,E0401
        - src/fetch/dune.py:12:0,E0401
        - src/fetch/dune.py:13:0,E0401
-   repo: local
    hooks:
    -   id: requirements
        name: requirements
        entry: pip install -r requirements.txt
        language: system
        pass_filenames: false
        always_run: true
    -   id: pytest
        name: pytest
        entry: pytest
        language: system
        types: [python]
        pass_filenames: false
        always_run: true
