name: pull request
on:
  pull_request:
  push:
    branches: [main]
jobs:
  python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install Requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint  # Add this line to explicitly install pylint
      - name: Pylint
        run: pylint src/
      - name: Black
        run: black --check ./
      - name: Type Check (mypy)
        run: mypy src --strict
      - name: Unit Tests
        run: python -m pytest tests/unit
